name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Fecth required Go modules
      run: go mod download
        
    - name: Build API
      run: go build -v ./...
    
    - name: Build Docker-Compose for test
      run: docker-compose -f docker-compose-dev.yml up -d

    - name: Run integration and unitary tests
      run: go test -v ./...
